import React, { useState, useEffect } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/components/ui/use-toast";
import {
  Shield,
  Mail,
  Lock,
  Key,
  Save,
  RefreshCcw,
  Eye,
  EyeOff,
  AlertCircle,
  CheckCircle2,
  FileDown,
} from "lucide-react";
import { motion } from "framer-motion";
import jsPDF from "jspdf";
import { useBranding } from "@/contexts/BrandingContext";

// ---------------------------------------------------------------------------
// PDF GENERATOR
// ---------------------------------------------------------------------------
const generateCredentialsPDF = (
  instituteName: string,
  email: string,
  password: string,
  secretKey: string,
) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const now = new Date();
  const dateStr = now.toLocaleString("en-PK", {
    dateStyle: "full",
    timeStyle: "short",
  });

  // ── Background header band ──────────────────────────────────────────────
  doc.setFillColor(20, 82, 204); // deep blue
  doc.roundedRect(0, 0, pageW, 48, 0, 0, "F");

  // ── Shield icon placeholder (circle) ────────────────────────────────────
  doc.setFillColor(255, 255, 255, 0.15);
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(0.5);
  doc.circle(pageW - 24, 16, 10, "S");

  // ── Institute name ───────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text(instituteName || "Institute", 14, 20);

  // ── Sub-title ────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(200, 220, 255);
  doc.text("Admin Credentials Backup  •  CONFIDENTIAL", 14, 30);

  // ── Date ─────────────────────────────────────────────────────────────────
  doc.setFontSize(8);
  doc.setTextColor(180, 210, 255);
  doc.text(`Generated: ${dateStr}`, 14, 40);

  // ── Card body ────────────────────────────────────────────────────────────
  doc.setFillColor(245, 247, 255);
  doc.roundedRect(10, 54, pageW - 20, 110, 4, 4, "F");

  // ── Section label ────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(20, 82, 204);
  doc.text("LOGIN DETAILS", 18, 66);

  // ── Divider ──────────────────────────────────────────────────────────────
  doc.setDrawColor(20, 82, 204);
  doc.setLineWidth(0.3);
  doc.line(18, 68, pageW - 18, 68);

  // ── Rows helper ──────────────────────────────────────────────────────────
  const drawRow = (
    label: string,
    value: string,
    y: number,
    highlight = false,
  ) => {
    if (highlight) {
      doc.setFillColor(230, 240, 255);
      doc.roundedRect(14, y - 5, pageW - 28, 14, 2, 2, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 100);
    doc.text(label, 18, y + 2);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(20, 20, 40);
    doc.text(value || "—", 70, y + 2);
  };

  drawRow("Admin Email", email, 78, true);
  drawRow("Password", password, 96);
  drawRow("Secret Key", secretKey, 114, true);
  drawRow("Last Updated", dateStr, 132);

  // ── Warning box ──────────────────────────────────────────────────────────
  doc.setFillColor(255, 243, 205);
  doc.setDrawColor(230, 160, 0);
  doc.setLineWidth(0.4);
  doc.roundedRect(10, 174, pageW - 20, 22, 3, 3, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(150, 80, 0);
  doc.text("⚠  Security Notice", 16, 183);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 60, 0);
  doc.text(
    "Keep this document in a safe place. Do not share it with anyone. Destroy after memorising.",
    16,
    190,
  );

  // ── Footer ───────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 180);
  doc.text(
    `${instituteName}  •  Auto-generated by CMS Admin System`,
    pageW / 2,
    285,
    { align: "center" },
  );

  doc.save("admin-credentials-backup.pdf");
};
// ---------------------------------------------------------------------------

const AdminCredentials: React.FC = () => {
  const { toast } = useToast();
  const { settings } = useBranding();
  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showSecretKey, setShowSecretKey] = useState(false);
  const [credentials, setCredentials] = useState({
    adminEmail: "",
    secretKey: "",
    isFixed: false,
    updatedAt: "",
  });
  const [formData, setFormData] = useState({
    adminEmail: "",
    password: "",
    confirmPassword: "",
    currentPassword: "",
  });

  const fetchCredentials = async () => {
    try {
      const res = await fetch("/api/admin/credentials", {
        credentials: "include",
      });
      if (res.ok) {
        const data = await res.json();
        setCredentials(data);
        setFormData((prev) => ({
          ...prev,
          adminEmail: data.adminEmail,
        }));
      }
    } catch (error) {
      console.error("Failed to fetch credentials:", error);
    }
  };

  useEffect(() => {
    fetchCredentials();
  }, []);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (formData.password && formData.password !== formData.confirmPassword) {
      toast({
        title: "Error",
        description: "New passwords do not match",
        variant: "destructive",
      });
      return;
    }

    if (!formData.currentPassword) {
      toast({
        title: "Required",
        description: "Please enter your current password to save changes",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      const res = await fetch("/api/admin/credentials", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          adminEmail: formData.adminEmail,
          password: formData.password || undefined,
          currentPassword: formData.currentPassword,
        }),
        credentials: "include",
      });

      if (res.ok) {
        // Auto-generate credentials backup PDF
        generateCredentialsPDF(
          settings.instituteFullName,
          formData.adminEmail,
          formData.password || "(unchanged)",
          credentials.secretKey || "CMS-CORE-SECURE-2026",
        );
        toast({
          title: "✅ Credentials Saved",
          description:
            "Credentials updated successfully. A PDF backup has been downloaded to your device.",
        });
        setFormData((prev) => ({
          ...prev,
          password: "",
          confirmPassword: "",
          currentPassword: "",
        }));
        fetchCredentials();
      } else {
        const err = await res.json();
        throw new Error(err.error || "Failed to update credentials");
      }
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const hasChanges =
    formData.adminEmail !== credentials.adminEmail || formData.password !== "";

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-4xl font-black text-neutral-900 tracking-tight">
            Admin Credentials
          </h2>
          <p className="text-neutral-500 mt-2 font-medium">
            Manage your secure login details and system access points.
          </p>
        </div>
        <div className="flex flex-col items-end gap-2">
          <div className="bg-blue-50 border border-blue-200 rounded-2xl p-4 flex items-center gap-3 max-w-md">
            <CheckCircle2 className="text-blue-600 shrink-0" size={20} />
            <p className="text-xs text-blue-800 font-medium">
              Secret Key is fixed to{" "}
              <span className="font-black">CMS-CORE-SECURE-2026</span> and
              cannot be changed.
            </p>
          </div>
          <div className="flex items-center gap-2 text-amber-600 bg-amber-50 px-3 py-1.5 rounded-lg border border-amber-100">
            <AlertCircle size={14} />
            <span className="text-xs font-bold">
              Changing admin credentials affects future logins.
            </span>
          </div>
        </div>
      </div>

      <Card className="rounded-3xl border-none bg-white shadow-xl shadow-neutral-200/40 overflow-hidden ring-1 ring-neutral-200/60 p-8">
        <form onSubmit={handleSubmit} className="max-w-3xl space-y-8">
          {/* Login Details */}
          <div className="space-y-6">
            <div className="flex items-center gap-2 mb-2">
              <span className="px-3 py-1 bg-primary/10 text-primary text-[10px] font-black uppercase tracking-widest rounded-full">
                Primary Access
              </span>
              <span className="h-[1px] flex-1 bg-neutral-100"></span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-sm font-black text-neutral-700 flex items-center gap-2">
                  <Mail size={14} className="text-primary" /> Admin Email
                </label>
                <Input
                  name="adminEmail"
                  value={formData.adminEmail}
                  onChange={handleChange}
                  className="h-12 rounded-xl"
                  placeholder="admin@example.com"
                />
              </div>

              <div className="space-y-2">
                <label className="text-sm font-black text-neutral-700 flex items-center gap-2">
                  <Key size={14} className="text-blue-600" /> Secret Key (Fixed)
                </label>
                <div className="relative">
                  <Input
                    type={showSecretKey ? "text" : "password"}
                    name="secretKey"
                    value={credentials.secretKey}
                    readOnly
                    className="h-12 rounded-xl pr-12 bg-blue-50 text-blue-900 cursor-not-allowed font-mono font-bold border-blue-200"
                  />
                  <div className="absolute right-2 top-1.5">
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      className="h-9 w-9 rounded-lg"
                      onClick={() => setShowSecretKey(!showSecretKey)}
                    >
                      {showSecretKey ? <EyeOff size={16} /> : <Eye size={16} />}
                    </Button>
                  </div>
                </div>
                <p className="text-xs text-blue-600 font-medium flex items-center gap-1">
                  <CheckCircle2 size={12} /> This value is system-protected and
                  cannot be modified
                </p>
              </div>
            </div>
          </div>

          {/* Change Password */}
          <div className="space-y-6">
            <div className="flex items-center gap-2 mb-2">
              <span className="px-3 py-1 bg-emerald-50 text-emerald-700 text-[10px] font-black uppercase tracking-widest rounded-full">
                Security Update
              </span>
              <span className="h-[1px] flex-1 bg-neutral-100"></span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label className="text-sm font-black text-neutral-700 flex items-center gap-2">
                  <Lock size={14} className="text-emerald-600" /> New Password
                </label>
                <div className="relative">
                  <Input
                    type={showPassword ? "text" : "password"}
                    name="password"
                    value={formData.password}
                    onChange={handleChange}
                    className="h-12 rounded-xl pr-12"
                    placeholder="Leave blank to keep same"
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="absolute right-2 top-1.5 h-9 w-9 rounded-lg"
                    onClick={() => setShowPassword(!showPassword)}
                  >
                    {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
                  </Button>
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-sm font-black text-neutral-700 flex items-center gap-2">
                  <Lock size={14} className="text-emerald-600" /> Confirm New
                  Password
                </label>
                <Input
                  type="password"
                  name="confirmPassword"
                  value={formData.confirmPassword}
                  onChange={handleChange}
                  className="h-12 rounded-xl"
                  placeholder="Repeat new password"
                />
              </div>
            </div>
          </div>

          {/* Verification & Submit */}
          <div className="pt-8 border-t border-neutral-100 space-y-6">
            <div className="bg-primary/5 rounded-3xl p-6 border border-primary/10">
              <div className="flex flex-col md:flex-row items-center gap-6">
                <div className="space-y-2 flex-1 w-full">
                  <label className="text-sm font-black text-primary flex items-center gap-2">
                    <Shield size={16} /> Confirm Current Password
                  </label>
                  <Input
                    type="password"
                    name="currentPassword"
                    value={formData.currentPassword}
                    onChange={handleChange}
                    className="h-12 rounded-xl bg-white border-primary/20 focus:border-primary"
                    placeholder="Enter your current password to authorize"
                  />
                </div>
                <Button
                  type="submit"
                  disabled={loading || !hasChanges}
                  className="h-14 px-8 rounded-2xl font-black text-lg bg-primary hover:bg-primary/90 shadow-lg shadow-primary/20 transition-all gap-2 min-w-[200px]"
                >
                  {loading ? (
                    <RefreshCcw size={20} className="animate-spin" />
                  ) : (
                    <Save size={20} />
                  )}
                  Save Changes
                </Button>
              </div>
            </div>

            {credentials.updatedAt && (
              <p className="text-center text-[10px] font-bold text-neutral-400 uppercase tracking-widest">
                Last updated: {new Date(credentials.updatedAt).toLocaleString()}
              </p>
            )}
          </div>
        </form>
      </Card>
    </div>
  );
};

export default AdminCredentials;
